version: '2'
services:
  api-seguranca-comunicacao-mysql:
    image: mysql:8.0.19
    volumes:
         - ~/volumes/tccsca/ApiSegurancaComunicacao/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=2mAn35b7tzse
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DATABASE=tccscapucminasbackendapisegurancacomunicacao
    ports:
      - "3308:3306"
    expose:
      - "3306"
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
